apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: url-shortener
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  DATABASE_URL: postgresql://postgres:admin@postgres-service:5432/postgres